/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include "ringbuf.h"
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void setUp(void);
extern void tearDown(void);
extern void test_ringbuf_init(void);
extern void test_ringbuf_put(void);
extern void test_ringbuf_get(void);
extern void test_ringbuf_clear(void);
extern void test_ringbuf_put_while_full(void);
extern void test_ringbuf_get_while_empty(void);
extern void test_ringbuf_loop_when_needed(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void);
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void);
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("test/ringbuf_test.c");
  run_test(test_ringbuf_init, "test_ringbuf_init", 32);
  run_test(test_ringbuf_put, "test_ringbuf_put", 52);
  run_test(test_ringbuf_get, "test_ringbuf_get", 73);
  run_test(test_ringbuf_clear, "test_ringbuf_clear", 106);
  run_test(test_ringbuf_put_while_full, "test_ringbuf_put_while_full", 140);
  run_test(test_ringbuf_get_while_empty, "test_ringbuf_get_while_empty", 171);
  run_test(test_ringbuf_loop_when_needed, "test_ringbuf_loop_when_needed", 193);

  return UnityEnd();
}
